### ISSUE TITLE
7.0取消了网络变化广播？

### ISSUE THREAD

**Issue by jp1017** [ssyijiu/android-helper#1]
7.0取消了网络变化广播吗？那你是如何处理网络变化的呢 :100:

**Comment by ssyijiu** [comment]
抱歉，今天才看到。又去翻了下官方文档，移除了  CONNECTIVITY_ACTION ，CONNECTIVITY_CHANGE 还是可以用的，https://developer.android.com/about/versions/nougat/android-7.0-changes.html?hl=pa#bg-opt。NetUtil 已经更新

**Comment by jp1017** [comment]
感谢！
